use master
go 
if exists(select * from sysdatabases where name = 'QuanLyQuanCoffee' )
	drop database QuanLyQuanCoffee

Create database QuanLyQuanCoffee
go 
use QuanLyQuanCoffee
CREATE TABLE NHACUNGCAP
(
  MaNCC Char(4) NOT NULL,
  TenNCC Nvarchar(30) NOT NULL,
  DiaChi Nvarchar(100),
  SoDT Char(11),
  PRIMARY KEY (MaNCC),
);

CREATE TABLE KHACHHANG
(
  MaKH Char(6) NOT NULL,
  HoTenKH Nvarchar(50) NOT NULL,
  DiaChi Nvarchar(100),
  GioiTinh Nvarchar(3),
  SoDTKH Char(11),
  PRIMARY KEY (MaKH)
);
CREATE TABLE NHANVIEN
(
  MaNV Char(4) NOT NULL,
  TenNV Nvarchar(50) NOT NULL, 
  SoDT Char(11),
  GioiTinh Nvarchar(3),
  DiaChi Nvarchar(100),
  NgaySinh Date,
  ChucVu Nvarchar(20),
  PRIMARY KEY (MaNV)
);

CREATE TABLE TAIKHOAN
(
  TenDN Varchar(100) NOT NULL,
  MatKhau Varchar(50) NOT NULL,
  PhanQuyen Varchar(1),
  MaKH Char(6), -- Chỉnh sửa độ dài của cột MaKH thành 6
  MaNV Char(4),
  PRIMARY KEY (TenDN),
  CONSTRAINT FK_KHACHHANG_TAIKHOAN FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
  CONSTRAINT FK_NHANVIEN_TAIKHOAN FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);

Create table SHIPPER
(
	MaShipper Char(4),
	TenShipper nvarchar(40)
	primary key (MaShipper) 
);

CREATE TABLE HOADON
(
  MaHD Char(6) NOT NULL,
  NgayTD Date,
  TongGiaTriHD INT ,
  GhiChu Nvarchar(50),
  TrangThaiDH nvarchar(50),
  MaShipper char(4),
  MaKH Char(6) NOT NULL,
  MaNV Char(4) NOT NULL,
  PRIMARY KEY (MaHD),
  CONSTRAINT FK_SHIPPER_HOADON FOREIGN KEY (MaShipper) REFERENCES SHIPPER(MaShipper),
  CONSTRAINT FK_NHANVIEN_HOADON FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
  CONSTRAINT FK_KHACHHANG_HOADON FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
);
CREATE TABLE LOAISANPHAM
(
	MaLoaiSP char(4),
	TenLoaiSP Nvarchar(30),
	MaNCC Char(4) ,
	Primary key(MaLoaiSP),
	CONSTRAINT FK_NHACUNGCAP_LOAISANPHAM FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC)
	);

CREATE TABLE SANPHAM
(
  MaSP Char(4) NOT NULL,
  TenSP Nvarchar(50) NOT NULL,
  GiaSP INT NOT NULL,
  SoLuongSP INT,
  MaLoaiSP Char(4),
  NgaySX Date,
  PRIMARY KEY (MaSP),
  Constraint FK_LOAISANPHAM_SANPHAM Foreign key ( MaLoaiSP) references LOAISANPHAM(MaLoaiSP)
);

CREATE TABLE KHUYENMAI
(
  MaKM Char(4) NOT NULL,
  TenKM Nvarchar(50) NOT NULL,
  GiaTriKM INT NOT NULL,
  PRIMARY KEY (MaKM)
);

CREATE TABLE CHITIET_HOADON
(
  MaHD Char(6) NOT NULL,
  MaSP Char(4) NOT NULL,
  Soluong Int,
  MaKM char(4),
  TongTien INT,
  UnitPrice  INT      NOT NULL,
  TotalPrice AS       ([Soluong]*[UnitPrice]) PERSISTED,
  PRIMARY KEY(MaHD,MaSP),
  CONSTRAINT FK_SANPHAM_CHITIETHOADON FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP),
  CONSTRAINT FK_KHUYENMAI_CHITIETHOADON FOREIGN KEY (MaKM) REFERENCES KHUYENMAI(MaKM),
  CONSTRAINT FK_HOADON_CHITIETHOADON FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD)
);
CREATE TABLE KHO
(
  MaHH Char(4) NOT NULL,
  TenHH Nvarchar(50) NOT NULL,
  SoLuongNhap INT NOT NULL,
  GiaHH INT ,
  MaNCC Char(4),
  PRIMARY KEY (MaHH),
  CONSTRAINT FK_NHACUNGCAP_KHO FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC)
);
CREATE TABLE DANHGIA
(
  MaDG Char(4) NOT NULL,
  MaKH Char(6) NOT NULL,
  SoSao INT CHECK (SoSao >= 1 AND SoSao <= 5),
  NoiDung Nvarchar(255),
  NgayDanhGia Date NOT NULL,
  PRIMARY KEY (MaDG),
  CONSTRAINT FK_KHACHHANG_DANHGIA FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
);

CREATE TABLE MAU
(
 MaMau int,
 TenMau Nvarchar(30),
 RGB Nvarchar(Max)
 PRIMARY KEY(MaMau)
);

ALTER TABLE SANPHAM ADD MaMau int
ALTER TABLE SANPHAM ADD CONSTRAINT FK_MAMAU_SANPHAM FOREIGN KEY (MaMau) REFERENCES MAU(MaMau)

CREATE TABLE PRODUCT
(
IDPro Char (4) Primary Key (IDPro),
NamePro Nvarchar(100),
Desciption Nvarchar(max),
Img1 Nvarchar(max),
Img2 Nvarchar(max),
Img3 Nvarchar(max)

);


Alter table SANPHAM add IDPro Char(4) 
Alter table SANPHAM add CONSTRAINT FK_PRODUCT_SANPHAM FOREIGN KEY (IDPro) REFERENCES PRODUCT(IDPro)
Alter table SANPHAM add SoLuongDaBan int

ALTER TABLE SANPHAM DROP CONSTRAINT FK_LOAISANPHAM_SANPHAM 

ALTER TABLE SANPHAM DROP COLUMN MaLoaiSP

ALTER TABLE PRODUCT ADD MaLoaiSP char(4)
ALTER TABLE PRODUCT ADD CONSTRAINT FK_LOAISANPHAM_PRODUCT FOREIGN KEY (MaLoaiSP) REFERENCES LOAISANPHAM(MaLoaiSP)

ALTER TABLE HOADON DROP CONSTRAINT FK_NHANVIEN_HOADON
ALTER TABLE HOADON DROP CONSTRAINT FK_KHACHHANG_HOADON

ALTER TABLE HOADON DROP COLUMN MaKH
ALTER TABLE HOADON DROP COLUMN MaNV
ALTER TABLE HOADON ADD TenDN Varchar(100)

ALTER TABLE HOADON ADD CONSTRAINT FK_TAIKHOAN_HOADON FOREIGN KEY (TenDN) REFERENCES TAIKHOAN(TenDN)
ALTER TABLE HOADON ADD HoTenKH Nvarchar(50) NOT NULL
ALTER TABLE HOADON ADD SDT Nvarchar(11) NOT NULL

ALTER TABLE TAIKHOAN
ADD Email Nvarchar(50)


CREATE TABLE DUNGLUONG
(
	MaDungLuong INT PRIMARY KEY IDENTITY(1,1) ,
	KichThuocDL Nvarchar(50) NOT NULL
)

ALTER TABLE SANPHAM
ADD MaDungLuong INT

ALTER TABLE SANPHAM
ADD CONSTRAINT FK_DUNGLUONG_SANPHAM FOREIGN KEY (MaDungLuong) REFERENCES DUNGLUONG(MaDungLuong)

ALTER TABLE LOAISANPHAM DROP CONSTRAINT FK_NHACUNGCAP_LOAISANPHAM
ALTER TABLE LOAISANPHAM DROP COLUMN MaNCC

ALTER TABLE KHO DROP CONSTRAINT FK_NHACUNGCAP_KHO
ALTER TABLE KHO DROP COLUMN MaNCC

ALTER TABLE SANPHAM DROP CONSTRAINT FK_NHACUNGCAP_KHO
ALTER TABLE KHO DROP COLUMN MaNCC

DROP TABLE KHO

CREATE TABLE KHO(
MaKho INT PRIMARY KEY IDENTITY(1,1),
MaSP Char(4) UNIQUE, --Mỗi sản phẩm chỉ có một bản ghi trong kho
MaNCC Char(4) NOT NULL, 
SoLuongTon INT NOT NULL CHECK(SoLuongTon >= 0),
LastUpdate DATETIME DEFAULT GETDATE()
CONSTRAINT FK_SANPHAM_KHO FOREIGN KEY(MaSP) REFERENCES SANPHAM(MaSP) ON DELETE CASCADE,
CONSTRAINT FK_NHACUNGCAP_KHO FOREIGN KEY(MaNCC) REFERENCES NHACUNGCAP(MaNCC) ON DELETE CASCADE
)





