//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCoffee.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.SANPHAMs = new HashSet<SANPHAM>();
        }

        public string IDPro { get; set; }
        public string NamePro { get; set; }
        public string Desciption { get; set; }
        public string Img1 { get; set; }
        public string Img2 { get; set; }
        public string Img3 { get; set; }
        public string MaLoaiSP { get; set; }
        [Required(ErrorMessage = "Hay chon file anh")]
        //[RegularExpression(@"[a-zA-Z0-9\s_\\.\-:] + (.png|.jpg|.gif)$",ErrorMessage = "Chi nhan dinh dang .PNG, .JPG , .GIF")]
        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; } //Anh 1

        [Required(ErrorMessage = "Hay chon file anh")]
        //[RegularExpression(@"[a-zA-Z0-9\s_\\.\-:] + (.png|.jpg|.gif)$",ErrorMessage = "Chi nhan dinh dang .PNG, .JPG , .GIF")]
        [NotMapped]
        public HttpPostedFileBase UploadImage1 { get; set; } //Anh 1

        [Required(ErrorMessage = "Hay chon file anh")]
        //[RegularExpression(@"[a-zA-Z0-9\s_\\.\-:] + (.png|.jpg|.gif)$",ErrorMessage = "Chi nhan dinh dang .PNG, .JPG , .GIF")]
        [NotMapped]
        public HttpPostedFileBase UploadImage2 { get; set; } //Anh 1

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
    }
}
