//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations.Schema; // B? sung NotMapped
using System.Web; // B? sung HttpPostedFileBase
namespace QLCoffee.Models
{
    using System;
    using System.Collections.Generic;

    public partial class PRODUCT
    {
        [NotMapped] // Thu?c tính này không ???c l?u vào database
        public HttpPostedFileBase UploadImage { get; set; }

        [NotMapped]
        public HttpPostedFileBase UploadImage1 { get; set; }

        [NotMapped]
        public HttpPostedFileBase UploadImage2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.SANPHAMs = new HashSet<SANPHAM>();
        }

        public string IDPro { get; set; }
        public string NamePro { get; set; }
        public string Desciption { get; set; }
        public string Img1 { get; set; }
        public string Img2 { get; set; }
        public string Img3 { get; set; }
        public string MaLoaiSP { get; set; }

        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}