//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCoffee.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TAIKHOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAIKHOAN()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
        [DisplayName("TenDN")]
        [Required(ErrorMessage = "Không được bỏ trống tên đăng nhập.")]

        public string TenDN { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Không được bỏ trống Email.")]
        public string Email { get; set; }

        [DisplayName("MatKhau")]
        [Required(ErrorMessage = "Không được bỏ trống mật khẩu.")]
        public string MatKhau { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "Vui lòng xác thực mật khẩu.")]
        [Compare("MatKhau")]
        public string RePass { get; set; }

        private string _PhanQuyen;
        [DisplayName("PhanQuyen")]
        [Required(ErrorMessage = "Không được bỏ trống phân quyền.")]
        [StringLength(1, ErrorMessage = "PhanQuyen save only 1 character")]
        public string PhanQuyen
        {
            get { return _PhanQuyen; }
            set { _PhanQuyen = value?.Trim(); }
        }
        public string MaKH { get; set; }
        public string MaNV { get; set; }

        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
